version: '3.7'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - webnet
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  bartr:
    container_name: bartr
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${BARTR_POSTGRES_PASSWORD}
      POSTGRES_USER: ${BARTR_POSTGRES_USERNAME}
      POSTGRES_DB: ${BARTR_POSTGRES_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet:
volumes:
  pgdata:
